Feature/add webpack
omega-code/place-selector pull request #1
Opened 2016-11-03 08:16 UTC by Traveler59

2016-11-03 10:46 UTC, AndreyTsvetkov requested changes
Я описал мои замечания по ЗС, жду новой версии :) спасибо за четкое исполнение!

2016-11-03 10:46 UTC, AndreyTsvetkov commented on src/ts/typings/interact-patched.ts
>  // Definitions by: Gaspard Bucher <feature-space.com>
Почему он стал из .d.ts -> .ts? Если без причины, то тогда верни .d.ts

2016-11-03 10:46 UTC, AndreyTsvetkov commented on tsconfig.json
> +        "module": "commonjs"
Давай используем возможности TS 2.0 полностью, как тут https://github.com/AndreyTsvetkov/react-bootstrap-mobx-ts-webpack/blob/master/tsconfig.json. Ключевое — strictNullChecks, experimentalDecorators. Но и остальные тоже полезные. Больше контроля от компилятора — меньше циклов код ревью :)

2016-11-03 10:46 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +import interact = require('interact.js');
верно ли я понимаю, что interact.js реализован как `export  = ...`-модуль, и поэтому его нужно импортировать через `= require(...)`? (согласно [описанию модулей в TS](http://www.typescriptlang.org/docs/handbook/modules.html) )

2016-11-03 10:46 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +var pixelSize = 10, placeSize = pixelSize + 2;
Всегда используем минимально достаточную область видимости и изменчивость. То есть, `private` лучше, чем `public`, `const` лучше, чем `let`,  и `let` лучше, чем `var` везде, где возможно. Если можно немного изменить код, но избавиться от `let` в пользу `const`, стоит это сделать. `var` вообще не вижу причин использовать.

2016-11-03 10:46 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +    allPlaces : function(): number {
`:` всегда обрамляем двумя пробелами: `function() : number`

2016-11-03 10:46 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +var dragStart:InteractEvent, dragEnd:InteractEvent;
Глобальные переменные намекают нам на то, что нужно создать класс для управления этим канвасом, и подумать, какой компонент получается, и хорошо его назвать. Переменные должны стать внутренним состоянием класса.

2016-11-03 10:46 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +        dragEnd = event;
а обработчики - методами в классе

2016-11-03 10:46 UTC, AndreyTsvetkov commented on package.json
> +        "ts-loader": "^0.9.5",
ts-loader и typescript — devDeps, а не runtime

2016-11-07 13:29 UTC, Traveler59 commented on src/ts/app.ts
> +import interact = require('interact.js');
И тайпинги и сам модуль interact.js из node_modules экспортируются через `export = `

2016-11-07 13:37 UTC, Traveler59 commented on src/ts/app.ts
> +        self.ctx = canv.getContext('2d');
При `"strictNullChecks": true` компилятор выдаёт ошибку, что `ctx` может оказаться `null` (что справедливо) в случае, если у `canv` окажется другой типа контекста, не '2d'.

2016-11-07 13:41 UTC, Traveler59 commented on src/ts/app.ts
> +const auditorium = new SeatSelector(canv, 10, 15);
Если установить `"noUnusedLocals": true` то будет ошибка неиспользования локальной переменной. Класс создан так, что в конструкторе происходит вся необходимая инициализация, в том числе назначение на обработчики методов класса SeatSelector

2016-11-07 13:51 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +        self.ctx = canv.getContext('2d');
и замечательно, давайте проверим это проверкой, и упадем в противном случае с сообщением, что у него «другой типа контекста, не '2d'»

2016-11-07 13:52 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +const auditorium = new SeatSelector(canv, 10, 15);
и ок, пусть тогда пока они не будут членами класса, а только параметрами конструктора

2016-11-07 14:11 UTC, Traveler59 commented on src/ts/app.ts
> +const auditorium = new SeatSelector(canv, 10, 15);
Не совсем понял, что вы имеете ввиду. Стоит передавать методы-обработчики в конструктор? 
Я имел ввиду что переменная `auditorium` нигде в коду не используется(так как функционирует и так)

2016-11-07 14:24 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +const auditorium = new SeatSelector(canv, 10, 15);
Да, неверно понял контекст. Значит в данном случае можем избавиться от этой переменной, я бы это сделал как-то так: `/*const auditorium = */new SeatsSelector(...)`, в предположении, что  со временем нам таки понадобится эта переменная.

2016-11-07 16:26 UTC, Traveler59 reviewed
Теперь всё вроде отлично. Спасибо за подсказку насчёт неиспользуемой переменной, я и не додумался сразу

2016-11-08 12:16 UTC, AndreyTsvetkov approved these changes

2016-11-08 12:17 UTC, merged