Feature/add seatings render
omega-code/place-selector pull request #5
Opened 2016-11-11 13:23 UTC by Traveler59

2016-11-11 20:12 UTC, AndreyTsvetkov requested changes

2016-11-11 20:12 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +class Rect {
классы выносим в отдельные файлы Rect.ts и тд

2016-11-11 20:12 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +    constructor(id : number, x : number, y : number, width : number, height : number, fill : string, ctx : CanvasRenderingContext2D) {
сократим этот код строк на 20 используя синтаксис "поля из параметров конструктора" `constructor(private id: number)`

2016-11-11 20:12 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +    constructor(id : number, x : number, y : number, width : number, height : number, fill : string, ctx : CanvasRenderingContext2D) {
мой косяк — в прошлый раз, прося привести все : к одному виду, разум мой помутился, и я сказал все обрамлять пробелами с двух сторон. прошу прощения за неточность, но общепринятый стандарт — `const a: string`, то есть пробел _после_

2016-11-11 20:12 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +        this.draw();
если можем безболезненно убрать этот вызов из конструктора, лучше сделать это. нарушаем [SRP](https://en.wikipedia.org/wiki/SRP). Поясню. Удобнее оперировать с объектами, когда в конструкторе не делаются значимые дела. Инициализируется все, подготавливается к работе — но не делается сама работа. Так получается разнести во времени создание и функционирование объекта, а это часто полезно. А если нужно создать и сразу запустить — ничто не мешает сделать `const smth = new Smth(); smth.Act();`

2016-11-11 20:12 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +    public isPointInside(x : number, y : number) : boolean {
сюда тогда лучше `Coords`

2016-11-11 20:12 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +        if(this.x >= area.begin.x && this.x <= area.end.x && this.y >= area.begin.y && this.y <= area.end.y)
очень много условий в одной строке, тяжело читается. либо надо их предвычислить и дать имена как булевским константам, либо — лучше — выразить это как `this.leftTop().isAfterOrEqual(area.begin) && this.rightBottom().isBeforeOrEqual(area.end)`

2016-11-11 20:12 UTC, AndreyTsvetkov commented on src/ts/app.ts
>  interface Coords {
чую, стать ей классом  с методами. типа belogsTo(area) и т.п. может сразу?) ну или не обязательно, просто держи это в уме

2016-11-11 20:12 UTC, AndreyTsvetkov commented on src/ts/app.ts
>      constructor(canvas : HTMLCanvasElement, pixelSize : number, placeSize : number) {
слишком длинный метод. разобраться невозможно, но и не нужно, так как метод длиной больше чем экран по-любому нарушает SRP :) подумай как это реорганизовать, чтобы было методов 5, короткие и с понятными именами

2016-11-11 20:12 UTC, AndreyTsvetkov commented on src/ts/app.ts
>      private dragMove(event : InteractEvent) : void {
разделить на несколько методов. блоки с похожим кодом явно просятся на вынесение в геометрические классы как методы

2016-11-13 18:27 UTC, Traveler59 commented on src/ts/app.ts
> +    constructor(id : number, x : number, y : number, width : number, height : number, fill : string, ctx : CanvasRenderingContext2D) {
Берегитесь, пробелы перед двоеточиями

2016-11-14 08:05 UTC, Traveler59 commented on src/ts/app.ts
> +class Rect {
У (пока что) интерфейсов `Coords` и `Area` есть использование и в `SeatSelector` и в `Rect`. Где их (интерфейсы) стоит разместить? Или тоже в отдельную директорию?

2016-11-14 08:12 UTC, AndreyTsvetkov commented on src/ts/app.ts
> +class Rect {
Про директорию я не вел речь, а отдельный файл тогда — да, конечно.

2016-11-15 19:58 UTC, AndreyTsvetkov commented on src/ts/Rect.ts
> +    constructor(readonly id: number, private x: number, private y: number, private width: number, private height: number, private fill: string, private ctx: CanvasRenderingContext2D) {}
мелочь, но — не больше 100 символов в строке, а желательно — и не сильно больше 80, перенести ее надо

2016-11-15 19:58 UTC, AndreyTsvetkov commented on src/ts/Rect.ts
> +    get rightBottom(): Coords {
!

2016-11-15 20:23 UTC, AndreyTsvetkov requested changes
отличная работа! и еще небольшая пачка изменений :) пусть я покажусь педантом. но это поможет нам всегда оставаться с кодом отличного качества, что стоит некоторых усилий по преодолению моих комментариев)

2016-11-15 20:23 UTC, AndreyTsvetkov commented on src/ts/SeatSelector.ts
> +    constructor(canvas: HTMLCanvasElement, pixelSize: number, placeSize: number) {
тут та же история с `private pixelSize: number`... или это специально с какой-то целью? тогда ее надо в комментарии отразить

2016-11-15 20:23 UTC, AndreyTsvetkov commented on src/ts/Coords.ts
> +    reset(): void {
такой класс, представляющий значение, как коордс, должен следовать паттерну [Value Object](http://martinfowler.com/bliki/ValueObject.html), в том числе быть неизменяемым, то есть убрать `reset`, сделать `x` `y` только для чтения

2016-11-15 20:23 UTC, AndreyTsvetkov commented on src/ts/SeatSelector.ts
> +            begin: new Coords,
а тут соответственно уже применен паттерн [NullObject](https://sourcemaking.com/design_patterns/null_object), что отлично, и стоит только сделать его более явным, например ввести у `Coords` статическое константное свойство `empty = new Coords();` и использовать тут

2016-11-15 20:23 UTC, AndreyTsvetkov commented on src/ts/SeatSelector.ts
> +        self.dragStartCoords = new Coords;
аналогично

2016-11-15 20:23 UTC, AndreyTsvetkov commented on src/ts/SeatSelector.ts
> +            console.log("Wrong context type");
в этом случае объект `SearSelector` разве остается валиден? если нет, то перехват нужен не тут, а на уровне всей программы

2016-11-15 20:23 UTC, AndreyTsvetkov commented on src/ts/SeatSelector.ts
> +            let key = event.which - 48;
wow, что значит `48`? нужна говорящая константа, из этого кода понять, какие же клавиши переключают режим я не могу, т.к. что за символы с кодами 49 и 50 — без гугления неизвестно

2016-11-15 20:23 UTC, AndreyTsvetkov commented on src/ts/SeatSelector.ts
> +        if(this.mode == 'draw') {
что-то уже видел эти строковые литералы в коде. нужна константа, чтобы исключить опечатку в каждом новом `'draw'`

2016-11-16 08:12 UTC, Traveler59 commented on src/ts/SeatSelector.ts
> +    constructor(canvas: HTMLCanvasElement, pixelSize: number, placeSize: number) {
Мне показалось удобно, когда в одном месте продекларированы все поля класса, то есть выше конструктора

2016-11-16 08:49 UTC, Traveler59 commented on src/ts/SeatSelector.ts
> +const MODES = {
Константа, соответствующая клавише один мне кажется, не должна входить в `SeatSelector`, да и режимы работы тоже. Выходит, из за появления новых глобальных объектов(чтоб от них избавиться) нужно создать ещё один класс, `App` например?

2016-11-16 09:52 UTC, AndreyTsvetkov commented on src/ts/SeatSelector.ts
> +const MODES = {
Вопрос, где они используются. Если бы мы занимались моделированием клавиатуры, то тогда твое заключение про константу 48 верно. Но в нашем смысловом контексте это имеет отношение лишь к деталям реализации управления SeatSelector, так что — им место как можно локальнее, `keyBoardKeyOne` — в методе, где она и используется (понадобится еще где-то в том же классе — поднимется на уровень класса), а `Mode` должен стать `enum Mode { Draw, Select }` или даже `const enum Mode { ...} `, рядом с классом, в котором используется. Отличие между двумя видами enum загугли сам пжл)

2016-11-16 09:59 UTC, AndreyTsvetkov requested changes
Ну по сути это будет последний цикл)

2016-11-16 09:59 UTC, AndreyTsvetkov commented on src/ts/Coords.ts
> +        return(this.x <= point.x &&  this.y <= point.y);
разное форматирование методов в 3 строках друг от друга. consistency наше все.

2016-11-16 09:59 UTC, AndreyTsvetkov commented on src/ts/SeatSelector.ts
> +const MODES = {
как писал выше, одну — в метод, вторую сделать enum-ом

2016-11-16 12:02 UTC, AndreyTsvetkov requested changes
last fix

2016-11-16 12:02 UTC, AndreyTsvetkov commented on src/ts/SeatSelector.ts
> +const enum modes {
1) Имя типа — PascalCase (`modes` -> `Modes`)
2) Имя enum дается: 
- в единственном числе, когда это взаимоисключающие варианты: `enum PatientState { Alive, Dead }`
- во множественном, когда это дополняющие варианты, которые можно объединять через побитовое "или": `const enum Rights { None = 0, Read = 1, Write = 2, ReadWrite = 3 /*3 === 1 | 2*/ }`


так что `Modes` -> `Mode`

2016-11-16 12:07 UTC, Traveler59 commented on src/ts/SeatSelector.ts
> +const enum modes {
Сбили меня https://www.typescriptlang.org/docs/handbook/enums.html . Там сначала `Direction` а ниже - `Directions`

2016-11-16 12:19 UTC, AndreyTsvetkov approved these changes
Ура :)

2016-11-16 12:19 UTC, merged